import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const tokenFiles = [
  "colors",
  "typography",
  "spacing",
  "radius",
  "shadows",
  "components",
];

const raw = Object.fromEntries(
  tokenFiles.map((name) => [
    name,
    JSON.parse(readFileSync(new URL(`./tokens/${name}.json`, import.meta.url), "utf8")),
  ])
);

const componentRules = JSON.parse(
  readFileSync(new URL("./tokens/component-rules.json", import.meta.url), "utf8")
);

function collectTokens(obj, path = []) {
  const results = [];

  for (const [key, value] of Object.entries(obj)) {
    if (key.startsWith("$")) continue;

    if (value && typeof value === "object" && "$value" in value) {
      results.push({ path: [...path, key], token: value });
    } else if (value && typeof value === "object") {
      results.push(...collectTokens(value, [...path, key]));
    }
  }

  return results;
}

function kebab(input) {
  return input
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/[%]/g, "")
    .replace(/[_.\s]+/g, "-")
    .toLowerCase();
}

function toKebab(parts) {
  return parts.map(kebab).filter(Boolean).join("-");
}

function toCamel(parts) {
  const name = toKebab(parts);
  return name.replace(/-([a-z0-9])/g, (_, char) => char.toUpperCase());
}

const tokens = tokenFiles.flatMap((name) => collectTokens(raw[name]));
const tokenLookup = new Map(
  tokens.map(({ path, token }) => [path.join("."), token.$value])
);

function resolveValue(value) {
  if (Array.isArray(value)) return value.map(resolveValue);

  if (value && typeof value === "object") {
    return Object.fromEntries(
      Object.entries(value).map(([key, nestedValue]) => [key, resolveValue(nestedValue)])
    );
  }

  if (typeof value !== "string") return value;

  return value.replace(/\{([^}]+)\}/g, (_, ref) => {
    const resolved = tokenLookup.get(ref);
    return typeof resolved === "string" ? resolveValue(resolved) : String(resolved ?? `{${ref}}`);
  });
}

function variableLinesForToken(path, value) {
  const resolved = resolveValue(value);

  if (resolved && typeof resolved === "object") {
    return Object.entries(resolved).map(
      ([key, nestedValue]) =>
        `  --${toKebab([...path, key])}: ${resolveValue(nestedValue)};`
    );
  }

  return [`  --${toKebab(path)}: ${resolved};`];
}

function generateVariablesCss() {
  const lines = [
    "/* Auto-generated by Imani DS build - DO NOT EDIT */",
    ":root {",
  ];

  for (const { path, token } of tokens) {
    lines.push(...variableLinesForToken(path, token.$value));
  }

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function generateTokensTs() {
  const lines = [
    "/* Auto-generated by Imani DS build - DO NOT EDIT */",
    "",
    "export const tokens = {",
  ];

  for (const { path, token } of tokens) {
    const resolved = resolveValue(token.$value);
    lines.push(`  ${toCamel(path)}: ${JSON.stringify(resolved)},`);
  }

  lines.push("} as const;");
  lines.push("");

  for (const { path, token } of tokens) {
    const resolved = resolveValue(token.$value);
    lines.push(`export const ${toCamel(path)} = ${JSON.stringify(resolved)} as const;`);
  }

  return lines.join("\n") + "\n";
}

function generateTailwindPreset() {
  const colors = {};
  const spacing = {};
  const borderRadius = {};
  const boxShadow = {};
  const fontFamily = {};
  const fontSize = {};
  const fontWeight = {};
  const lineHeight = {};
  const letterSpacing = {};

  for (const { path, token } of tokens) {
    const cssVar = `var(--${toKebab(path)})`;
    const value = resolveValue(token.$value);

    if (path[0] === "color") {
      colors[path.slice(1).map(kebab).join("-")] = cssVar;
    }

    if (path[0] === "spacing") {
      spacing[path.slice(1).map(kebab).join("-")] = cssVar;
    }

    if (path[0] === "radius") {
      borderRadius[path[1]] = cssVar;
    }

    if (path[0] === "shadow") {
      boxShadow[path[1]] = cssVar;
    }

    if (path[0] === "font" && path[1] === "family") {
      fontFamily[kebab(path[2])] = [cssVar];
    }

    if (path[0] === "font" && path[1] === "size") {
      fontSize[kebab(path[2])] = cssVar;
    }

    if (path[0] === "font" && path[1] === "weight") {
      fontWeight[kebab(path[2])] = String(value);
    }

    if (path[0] === "font" && path[1] === "lineHeight") {
      lineHeight[kebab(path[2])] = cssVar;
    }

    if (path[0] === "font" && path[1] === "letterSpacing") {
      letterSpacing[kebab(path[2])] = cssVar;
    }
  }

  return [
    "/* Auto-generated by Imani DS build - DO NOT EDIT */",
    `const imaniPreset = ${JSON.stringify(
      {
        theme: {
          extend: {
            colors,
            spacing,
            borderRadius,
            boxShadow,
            fontFamily,
            fontSize,
            fontWeight,
            lineHeight,
            letterSpacing,
          },
        },
      },
      null,
      2
    )};`,
    "",
    "export default imaniPreset;",
    "",
  ].join("\n");
}

function generateRules() {
  const lines = [
    "<!-- Auto-generated by Imani DS build - DO NOT EDIT MANUALLY -->",
    "",
    "# Imani Design System Rules",
    "",
    "All Imani UI must consume the generated design tokens from `generated/variables.css`, `generated/tokens.ts`, or `generated/tailwind-preset.js`.",
    "",
    "## Theme",
    "",
    ...componentRules.theme.rules.map((rule) => `- ${rule}`),
    "",
    "## Assets",
    "",
    ...componentRules.assets.rules.map((rule) => `- ${rule}`),
    "",
    "## Component Rules",
    "",
    ...Object.entries(componentRules.components).map(
      ([name, rule]) => `- **${name}**: ${rule}`
    ),
    "",
    "## Source Token Files",
    "",
    ...tokenFiles.map((file) => `- \`tokens/${file}.json\``),
    "",
  ];

  return lines.join("\n");
}

mkdirSync(new URL("./generated", import.meta.url), { recursive: true });
mkdirSync(new URL("./public/resources", import.meta.url), { recursive: true });

const variablesCss = generateVariablesCss();
const tokensTs = generateTokensTs();
const tailwindPreset = generateTailwindPreset();
const rules = generateRules();

writeFileSync(new URL("./generated/variables.css", import.meta.url), variablesCss);
writeFileSync(new URL("./generated/tokens.ts", import.meta.url), tokensTs);
writeFileSync(new URL("./generated/tailwind-preset.js", import.meta.url), tailwindPreset);
writeFileSync(new URL("./DESIGN_RULES.md", import.meta.url), rules);
writeFileSync(new URL("./public/resources/variables.css", import.meta.url), variablesCss);
writeFileSync(new URL("./public/resources/tokens.ts", import.meta.url), tokensTs);
writeFileSync(new URL("./public/resources/tailwind-preset.js", import.meta.url), tailwindPreset);
writeFileSync(new URL("./public/resources/design-rules.md", import.meta.url), rules);

console.log("Generated Imani design tokens.");
