/* Auto-generated by Imani DS build - DO NOT EDIT */

export const tokens = {
  colorBrandTunicGreen: "#00CA00",
  colorBrandFenceGreen: "#073C2B",
  colorBrandAquaBliss: "#B8E0D9",
  colorBrandCloudBleach: "#F2F2F2",
  colorBrandBlackFeather: "#101C23",
  colorBrandWhite: "#FFFFFF",
  colorBrandAlphaTunicGreen50: "rgba(0, 202, 0, 0.5)",
  colorBrandAlphaTunicGreen30: "rgba(0, 202, 0, 0.3)",
  colorBrandAlphaTunicGreen12: "rgba(0, 202, 0, 0.12)",
  colorBrandAlphaFenceGreen90: "rgba(7, 60, 43, 0.9)",
  colorBrandAlphaFenceGreen72: "rgba(7, 60, 43, 0.72)",
  colorBrandAlphaFenceGreen12: "rgba(7, 60, 43, 0.12)",
  colorBrandAlphaWhite14: "rgba(255, 255, 255, 0.14)",
  colorBrandAlphaWhite10: "rgba(255, 255, 255, 0.1)",
  colorTextLightPrimary: "#101C23",
  colorTextLightHeading: "#073C2B",
  colorTextLightSecondary: "rgba(16, 28, 35, 0.72)",
  colorTextLightMuted: "rgba(16, 28, 35, 0.56)",
  colorTextLightInverse: "#FFFFFF",
  colorTextDarkPrimary: "oklch(0.98 0.005 165)",
  colorTextDarkHeading: "oklch(0.98 0.005 165)",
  colorTextDarkSecondary: "oklch(0.82 0.015 165)",
  colorTextDarkMuted: "oklch(0.72 0.02 165)",
  colorTextDarkAccent: "#B8E0D9",
  colorSurfacePage: "#FFFFFF",
  colorSurfacePageAlt: "#F2F2F2",
  colorSurfacePageWarm: "#FAFCF8",
  colorSurfaceCard: "#FFFFFF",
  colorSurfaceCardAlt: "#F2F2F2",
  colorSurfaceBrandDark: "oklch(0.16 0.02 175)",
  colorSurfaceBrandDarkRaised: "oklch(0.20 0.03 165)",
  colorSurfaceBrandDarkElevated: "oklch(0.24 0.04 165)",
  colorSurfaceBrandVivid: "#00CA00",
  colorSurfaceBrandSoft: "#B8E0D9",
  colorSurfacePopover: "#FFFFFF",
  colorSurfacePopoverDark: "oklch(0.20 0.03 165)",
  colorBorderSubtle: "#DCE6E2",
  colorBorderStrong: "#073C2B",
  colorBorderBrand: "#00CA00",
  colorBorderInverse: "rgba(255, 255, 255, 0.14)",
  colorStateSuccess: "#168A4A",
  colorStateSuccessSurface: "#DDF7E7",
  colorStateSuccessDark: "oklch(0.78 0.27 142)",
  colorStateInfo: "#197C86",
  colorStateInfoSurface: "#DDF4F2",
  colorStateInfoDark: "oklch(0.65 0.10 180)",
  colorStateWarning: "#9A6100",
  colorStateWarningSurface: "#FFF2CF",
  colorStateWarningDark: "oklch(0.82 0.16 85)",
  colorStateDanger: "#B8322A",
  colorStateDangerSurface: "#FBE3DF",
  colorStateDangerDark: "oklch(0.65 0.22 27)",
  colorStateFocus: "#B8E0D9",
  colorChartPrimary: "oklch(0.78 0.27 142)",
  colorChartSecondary: "oklch(0.88 0.05 175)",
  colorChartAccent: "oklch(0.65 0.10 180)",
  colorChartCool: "oklch(0.55 0.13 200)",
  colorChartWarning: "oklch(0.82 0.16 85)",
  colorChartSuccessDeep: "oklch(0.55 0.20 142)",
  colorChartDanger: "oklch(0.70 0.22 30)",
  colorChartIndigo: "oklch(0.55 0.07 240)",
  colorChartNeutral: "#586B63",
  colorChartGrid: "#DCE6E2",
  fontFamilyDisplay: "\"Agency\", \"Quicksand\", system-ui, sans-serif",
  fontFamilyBody: "\"DM Sans\", system-ui, sans-serif",
  fontFamilyMono: "ui-monospace, SFMono-Regular, \"SF Mono\", Consolas, monospace",
  fontWeightRegular: "400",
  fontWeightMedium: "500",
  fontWeightBold: "700",
  fontSizeCaption: "12px",
  fontSizeBodySm: "14px",
  fontSizeBody: "16px",
  fontSizeSubtitle: "22px",
  fontSizeH3: "28px",
  fontSizeH2: "44px",
  fontSizeH1: "64px",
  fontSizeDisplayLg: "96px",
  fontSizeDisplayXl: "160px",
  fontLineHeightCaption: "1.4",
  fontLineHeightBodySm: "1.5",
  fontLineHeightBody: "1.55",
  fontLineHeightSubtitle: "1.3",
  fontLineHeightH3: "1.25",
  fontLineHeightH2: "1.15",
  fontLineHeightH1: "1.1",
  fontLineHeightDisplayLg: "1.05",
  fontLineHeightDisplayXl: "0.95",
  fontLetterSpacingDefault: "0",
  typeRoleDisplayXl: {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"160px","fontWeight":"700","lineHeight":"0.95","letterSpacing":"0"},
  typeRoleDisplayLg: {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"96px","fontWeight":"700","lineHeight":"1.05","letterSpacing":"0"},
  typeRoleH1: {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"64px","fontWeight":"700","lineHeight":"1.1","letterSpacing":"0"},
  typeRoleH2: {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"44px","fontWeight":"700","lineHeight":"1.15","letterSpacing":"0"},
  typeRoleH3: {"fontFamily":"\"DM Sans\", system-ui, sans-serif","fontSize":"28px","fontWeight":"700","lineHeight":"1.25","letterSpacing":"0"},
  typeRoleBody: {"fontFamily":"\"DM Sans\", system-ui, sans-serif","fontSize":"16px","fontWeight":"400","lineHeight":"1.55","letterSpacing":"0"},
  typeRoleLabel: {"fontFamily":"\"DM Sans\", system-ui, sans-serif","fontSize":"14px","fontWeight":"500","lineHeight":"1.5","letterSpacing":"0"},
  spacing0: "0",
  spacing1: "4px",
  spacing2: "8px",
  spacing3: "12px",
  spacing4: "16px",
  spacing5: "24px",
  spacing6: "32px",
  spacing8: "48px",
  spacing10: "64px",
  spacing12: "96px",
  spacing16: "128px",
  spacingBase: "4px",
  spacingPageMarginDesktop: "64px",
  spacingPageMarginMobile: "24px",
  spacingGutterDesktop: "24px",
  spacingGutterMobile: "16px",
  spacingReadingWidth: "560px",
  radiusSm: "6px",
  radiusMd: "12px",
  radiusLg: "20px",
  radiusXl: "32px",
  radiusPill: "999px",
  shadowNone: "none",
  shadowSm: "0 1px 2px rgba(7, 60, 43, 0.06)",
  shadowMd: "0 6px 18px rgba(7, 60, 43, 0.10)",
  shadowLg: "0 18px 48px rgba(7, 60, 43, 0.16)",
  shadowFocus: "0 0 0 3px rgba(184, 224, 217, 0.7)",
  shadowFocusStrong: "0 0 0 4px rgba(184, 224, 217, 0.85)",
  componentButtonHeightCompact: "36px",
  componentButtonHeightDefault: "44px",
  componentButtonHeightHero: "56px",
  componentButtonPaddingXCompact: "16px",
  componentButtonPaddingXDefault: "24px",
  componentButtonPaddingXHero: "32px",
  componentButtonRadius: "12px",
  componentButtonFontFamily: "\"DM Sans\", system-ui, sans-serif",
  componentButtonFontSize: "16px",
  componentButtonFontWeight: "500",
  componentButtonPrimaryBg: "#00CA00",
  componentButtonPrimaryText: "#FFFFFF",
  componentButtonPrimaryHover: "#00BE00",
  componentButtonPrimaryActive: "#00B200",
  componentButtonSecondaryBg: "#073C2B",
  componentButtonSecondaryText: "#FFFFFF",
  componentButtonOutlineBorder: "#073C2B",
  componentButtonOutlineText: "#073C2B",
  componentButtonInverseBg: "#FFFFFF",
  componentButtonInverseText: "#073C2B",
  componentInputHeight: "44px",
  componentInputRadius: "12px",
  componentInputBorderWidth: "1.5px",
  componentInputBorder: "#DCE6E2",
  componentInputFocusBorder: "#00CA00",
  componentInputFocusRing: "#B8E0D9",
  componentInputBackground: "#FFFFFF",
  componentInputText: "#101C23",
  componentInputPlaceholder: "rgba(16, 28, 35, 0.56)",
  componentCardBackground: "#FFFFFF",
  componentCardBackgroundAlt: "#F2F2F2",
  componentCardRadius: "20px",
  componentCardPadding: "32px",
  componentCardGap: "16px",
  componentCardBorder: "#DCE6E2",
  componentCardPromoAccentHeight: "4px",
  componentBadgeHeight: "24px",
  componentBadgeRadius: "999px",
  componentBadgePaddingX: "12px",
  componentBadgeFontSize: "12px",
  componentBadgeFontWeight: "500",
  componentTabsListBg: "#F2F2F2",
  componentTabsTriggerHeight: "36px",
  componentTabsTriggerRadius: "12px",
  componentTabsActiveBg: "#FFFFFF",
  componentTabsActiveText: "#073C2B",
  componentTableRowHeight: "48px",
  componentTableHeaderText: "rgba(16, 28, 35, 0.72)",
  componentTableBorder: "#DCE6E2",
  componentOverlayDialogBg: "#FFFFFF",
  componentOverlayDialogDarkBg: "oklch(0.20 0.03 165)",
  componentOverlayRadius: "20px",
  componentOverlayShadow: "0 18px 48px rgba(7, 60, 43, 0.16)",
  componentOverlayBackdrop: "rgba(7, 60, 43, 0.32)",
  componentFocusRingWidth: "3px",
  componentFocusRingColor: "#B8E0D9",
  componentControlHeightCompact: "36px",
  componentControlHeightDefault: "44px",
  componentControlHeightLarge: "56px",
  componentControlRadius: "12px",
  componentControlLabelFontSize: "14px",
  componentControlLabelFontWeight: "500",
  componentControlSelectedBg: "#00CA00",
  componentControlSelectedText: "#FFFFFF",
  componentControlTrackBg: "#F2F2F2",
  componentControlTrackActiveBg: "#00CA00",
  componentControlThumbBg: "#FFFFFF",
  componentNavigationItemHeight: "40px",
  componentNavigationItemRadius: "12px",
  componentNavigationItemActiveBg: "#B8E0D9",
  componentNavigationItemActiveText: "#073C2B",
  componentNavigationItemMutedText: "rgba(16, 28, 35, 0.72)",
  componentNavigationBarBg: "#FFFFFF",
  componentNavigationBarBorder: "#DCE6E2",
  componentSidebarWidth: "280px",
  componentSidebarCollapsedWidth: "56px",
  componentSidebarBackground: "#F2F2F2",
  componentSidebarDarkBackground: "oklch(0.20 0.03 165)",
  componentSidebarBorder: "#DCE6E2",
  componentChartPrimary: "oklch(0.78 0.27 142)",
  componentChartSecondary: "oklch(0.88 0.05 175)",
  componentChartAccent: "oklch(0.65 0.10 180)",
  componentChartGrid: "#DCE6E2",
  componentChartBarRadius: "6px",
  componentEmptyMediaSize: "48px",
  componentEmptyTitleColor: "#073C2B",
  componentEmptyDescriptionColor: "rgba(16, 28, 35, 0.72)",
  componentEmptySurface: "#F2F2F2",
  componentLayoutMarketingColumns: "12",
  componentLayoutProductColumns: "8",
  componentLayoutCardGridMin: "280px",
  componentLayoutSectionPaddingDesktop: "96px",
  componentLayoutSectionPaddingMobile: "48px",
} as const;

export const colorBrandTunicGreen = "#00CA00" as const;
export const colorBrandFenceGreen = "#073C2B" as const;
export const colorBrandAquaBliss = "#B8E0D9" as const;
export const colorBrandCloudBleach = "#F2F2F2" as const;
export const colorBrandBlackFeather = "#101C23" as const;
export const colorBrandWhite = "#FFFFFF" as const;
export const colorBrandAlphaTunicGreen50 = "rgba(0, 202, 0, 0.5)" as const;
export const colorBrandAlphaTunicGreen30 = "rgba(0, 202, 0, 0.3)" as const;
export const colorBrandAlphaTunicGreen12 = "rgba(0, 202, 0, 0.12)" as const;
export const colorBrandAlphaFenceGreen90 = "rgba(7, 60, 43, 0.9)" as const;
export const colorBrandAlphaFenceGreen72 = "rgba(7, 60, 43, 0.72)" as const;
export const colorBrandAlphaFenceGreen12 = "rgba(7, 60, 43, 0.12)" as const;
export const colorBrandAlphaWhite14 = "rgba(255, 255, 255, 0.14)" as const;
export const colorBrandAlphaWhite10 = "rgba(255, 255, 255, 0.1)" as const;
export const colorTextLightPrimary = "#101C23" as const;
export const colorTextLightHeading = "#073C2B" as const;
export const colorTextLightSecondary = "rgba(16, 28, 35, 0.72)" as const;
export const colorTextLightMuted = "rgba(16, 28, 35, 0.56)" as const;
export const colorTextLightInverse = "#FFFFFF" as const;
export const colorTextDarkPrimary = "oklch(0.98 0.005 165)" as const;
export const colorTextDarkHeading = "oklch(0.98 0.005 165)" as const;
export const colorTextDarkSecondary = "oklch(0.82 0.015 165)" as const;
export const colorTextDarkMuted = "oklch(0.72 0.02 165)" as const;
export const colorTextDarkAccent = "#B8E0D9" as const;
export const colorSurfacePage = "#FFFFFF" as const;
export const colorSurfacePageAlt = "#F2F2F2" as const;
export const colorSurfacePageWarm = "#FAFCF8" as const;
export const colorSurfaceCard = "#FFFFFF" as const;
export const colorSurfaceCardAlt = "#F2F2F2" as const;
export const colorSurfaceBrandDark = "oklch(0.16 0.02 175)" as const;
export const colorSurfaceBrandDarkRaised = "oklch(0.20 0.03 165)" as const;
export const colorSurfaceBrandDarkElevated = "oklch(0.24 0.04 165)" as const;
export const colorSurfaceBrandVivid = "#00CA00" as const;
export const colorSurfaceBrandSoft = "#B8E0D9" as const;
export const colorSurfacePopover = "#FFFFFF" as const;
export const colorSurfacePopoverDark = "oklch(0.20 0.03 165)" as const;
export const colorBorderSubtle = "#DCE6E2" as const;
export const colorBorderStrong = "#073C2B" as const;
export const colorBorderBrand = "#00CA00" as const;
export const colorBorderInverse = "rgba(255, 255, 255, 0.14)" as const;
export const colorStateSuccess = "#168A4A" as const;
export const colorStateSuccessSurface = "#DDF7E7" as const;
export const colorStateSuccessDark = "oklch(0.78 0.27 142)" as const;
export const colorStateInfo = "#197C86" as const;
export const colorStateInfoSurface = "#DDF4F2" as const;
export const colorStateInfoDark = "oklch(0.65 0.10 180)" as const;
export const colorStateWarning = "#9A6100" as const;
export const colorStateWarningSurface = "#FFF2CF" as const;
export const colorStateWarningDark = "oklch(0.82 0.16 85)" as const;
export const colorStateDanger = "#B8322A" as const;
export const colorStateDangerSurface = "#FBE3DF" as const;
export const colorStateDangerDark = "oklch(0.65 0.22 27)" as const;
export const colorStateFocus = "#B8E0D9" as const;
export const colorChartPrimary = "oklch(0.78 0.27 142)" as const;
export const colorChartSecondary = "oklch(0.88 0.05 175)" as const;
export const colorChartAccent = "oklch(0.65 0.10 180)" as const;
export const colorChartCool = "oklch(0.55 0.13 200)" as const;
export const colorChartWarning = "oklch(0.82 0.16 85)" as const;
export const colorChartSuccessDeep = "oklch(0.55 0.20 142)" as const;
export const colorChartDanger = "oklch(0.70 0.22 30)" as const;
export const colorChartIndigo = "oklch(0.55 0.07 240)" as const;
export const colorChartNeutral = "#586B63" as const;
export const colorChartGrid = "#DCE6E2" as const;
export const fontFamilyDisplay = "\"Agency\", \"Quicksand\", system-ui, sans-serif" as const;
export const fontFamilyBody = "\"DM Sans\", system-ui, sans-serif" as const;
export const fontFamilyMono = "ui-monospace, SFMono-Regular, \"SF Mono\", Consolas, monospace" as const;
export const fontWeightRegular = "400" as const;
export const fontWeightMedium = "500" as const;
export const fontWeightBold = "700" as const;
export const fontSizeCaption = "12px" as const;
export const fontSizeBodySm = "14px" as const;
export const fontSizeBody = "16px" as const;
export const fontSizeSubtitle = "22px" as const;
export const fontSizeH3 = "28px" as const;
export const fontSizeH2 = "44px" as const;
export const fontSizeH1 = "64px" as const;
export const fontSizeDisplayLg = "96px" as const;
export const fontSizeDisplayXl = "160px" as const;
export const fontLineHeightCaption = "1.4" as const;
export const fontLineHeightBodySm = "1.5" as const;
export const fontLineHeightBody = "1.55" as const;
export const fontLineHeightSubtitle = "1.3" as const;
export const fontLineHeightH3 = "1.25" as const;
export const fontLineHeightH2 = "1.15" as const;
export const fontLineHeightH1 = "1.1" as const;
export const fontLineHeightDisplayLg = "1.05" as const;
export const fontLineHeightDisplayXl = "0.95" as const;
export const fontLetterSpacingDefault = "0" as const;
export const typeRoleDisplayXl = {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"160px","fontWeight":"700","lineHeight":"0.95","letterSpacing":"0"} as const;
export const typeRoleDisplayLg = {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"96px","fontWeight":"700","lineHeight":"1.05","letterSpacing":"0"} as const;
export const typeRoleH1 = {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"64px","fontWeight":"700","lineHeight":"1.1","letterSpacing":"0"} as const;
export const typeRoleH2 = {"fontFamily":"\"Agency\", \"Quicksand\", system-ui, sans-serif","fontSize":"44px","fontWeight":"700","lineHeight":"1.15","letterSpacing":"0"} as const;
export const typeRoleH3 = {"fontFamily":"\"DM Sans\", system-ui, sans-serif","fontSize":"28px","fontWeight":"700","lineHeight":"1.25","letterSpacing":"0"} as const;
export const typeRoleBody = {"fontFamily":"\"DM Sans\", system-ui, sans-serif","fontSize":"16px","fontWeight":"400","lineHeight":"1.55","letterSpacing":"0"} as const;
export const typeRoleLabel = {"fontFamily":"\"DM Sans\", system-ui, sans-serif","fontSize":"14px","fontWeight":"500","lineHeight":"1.5","letterSpacing":"0"} as const;
export const spacing0 = "0" as const;
export const spacing1 = "4px" as const;
export const spacing2 = "8px" as const;
export const spacing3 = "12px" as const;
export const spacing4 = "16px" as const;
export const spacing5 = "24px" as const;
export const spacing6 = "32px" as const;
export const spacing8 = "48px" as const;
export const spacing10 = "64px" as const;
export const spacing12 = "96px" as const;
export const spacing16 = "128px" as const;
export const spacingBase = "4px" as const;
export const spacingPageMarginDesktop = "64px" as const;
export const spacingPageMarginMobile = "24px" as const;
export const spacingGutterDesktop = "24px" as const;
export const spacingGutterMobile = "16px" as const;
export const spacingReadingWidth = "560px" as const;
export const radiusSm = "6px" as const;
export const radiusMd = "12px" as const;
export const radiusLg = "20px" as const;
export const radiusXl = "32px" as const;
export const radiusPill = "999px" as const;
export const shadowNone = "none" as const;
export const shadowSm = "0 1px 2px rgba(7, 60, 43, 0.06)" as const;
export const shadowMd = "0 6px 18px rgba(7, 60, 43, 0.10)" as const;
export const shadowLg = "0 18px 48px rgba(7, 60, 43, 0.16)" as const;
export const shadowFocus = "0 0 0 3px rgba(184, 224, 217, 0.7)" as const;
export const shadowFocusStrong = "0 0 0 4px rgba(184, 224, 217, 0.85)" as const;
export const componentButtonHeightCompact = "36px" as const;
export const componentButtonHeightDefault = "44px" as const;
export const componentButtonHeightHero = "56px" as const;
export const componentButtonPaddingXCompact = "16px" as const;
export const componentButtonPaddingXDefault = "24px" as const;
export const componentButtonPaddingXHero = "32px" as const;
export const componentButtonRadius = "12px" as const;
export const componentButtonFontFamily = "\"DM Sans\", system-ui, sans-serif" as const;
export const componentButtonFontSize = "16px" as const;
export const componentButtonFontWeight = "500" as const;
export const componentButtonPrimaryBg = "#00CA00" as const;
export const componentButtonPrimaryText = "#FFFFFF" as const;
export const componentButtonPrimaryHover = "#00BE00" as const;
export const componentButtonPrimaryActive = "#00B200" as const;
export const componentButtonSecondaryBg = "#073C2B" as const;
export const componentButtonSecondaryText = "#FFFFFF" as const;
export const componentButtonOutlineBorder = "#073C2B" as const;
export const componentButtonOutlineText = "#073C2B" as const;
export const componentButtonInverseBg = "#FFFFFF" as const;
export const componentButtonInverseText = "#073C2B" as const;
export const componentInputHeight = "44px" as const;
export const componentInputRadius = "12px" as const;
export const componentInputBorderWidth = "1.5px" as const;
export const componentInputBorder = "#DCE6E2" as const;
export const componentInputFocusBorder = "#00CA00" as const;
export const componentInputFocusRing = "#B8E0D9" as const;
export const componentInputBackground = "#FFFFFF" as const;
export const componentInputText = "#101C23" as const;
export const componentInputPlaceholder = "rgba(16, 28, 35, 0.56)" as const;
export const componentCardBackground = "#FFFFFF" as const;
export const componentCardBackgroundAlt = "#F2F2F2" as const;
export const componentCardRadius = "20px" as const;
export const componentCardPadding = "32px" as const;
export const componentCardGap = "16px" as const;
export const componentCardBorder = "#DCE6E2" as const;
export const componentCardPromoAccentHeight = "4px" as const;
export const componentBadgeHeight = "24px" as const;
export const componentBadgeRadius = "999px" as const;
export const componentBadgePaddingX = "12px" as const;
export const componentBadgeFontSize = "12px" as const;
export const componentBadgeFontWeight = "500" as const;
export const componentTabsListBg = "#F2F2F2" as const;
export const componentTabsTriggerHeight = "36px" as const;
export const componentTabsTriggerRadius = "12px" as const;
export const componentTabsActiveBg = "#FFFFFF" as const;
export const componentTabsActiveText = "#073C2B" as const;
export const componentTableRowHeight = "48px" as const;
export const componentTableHeaderText = "rgba(16, 28, 35, 0.72)" as const;
export const componentTableBorder = "#DCE6E2" as const;
export const componentOverlayDialogBg = "#FFFFFF" as const;
export const componentOverlayDialogDarkBg = "oklch(0.20 0.03 165)" as const;
export const componentOverlayRadius = "20px" as const;
export const componentOverlayShadow = "0 18px 48px rgba(7, 60, 43, 0.16)" as const;
export const componentOverlayBackdrop = "rgba(7, 60, 43, 0.32)" as const;
export const componentFocusRingWidth = "3px" as const;
export const componentFocusRingColor = "#B8E0D9" as const;
export const componentControlHeightCompact = "36px" as const;
export const componentControlHeightDefault = "44px" as const;
export const componentControlHeightLarge = "56px" as const;
export const componentControlRadius = "12px" as const;
export const componentControlLabelFontSize = "14px" as const;
export const componentControlLabelFontWeight = "500" as const;
export const componentControlSelectedBg = "#00CA00" as const;
export const componentControlSelectedText = "#FFFFFF" as const;
export const componentControlTrackBg = "#F2F2F2" as const;
export const componentControlTrackActiveBg = "#00CA00" as const;
export const componentControlThumbBg = "#FFFFFF" as const;
export const componentNavigationItemHeight = "40px" as const;
export const componentNavigationItemRadius = "12px" as const;
export const componentNavigationItemActiveBg = "#B8E0D9" as const;
export const componentNavigationItemActiveText = "#073C2B" as const;
export const componentNavigationItemMutedText = "rgba(16, 28, 35, 0.72)" as const;
export const componentNavigationBarBg = "#FFFFFF" as const;
export const componentNavigationBarBorder = "#DCE6E2" as const;
export const componentSidebarWidth = "280px" as const;
export const componentSidebarCollapsedWidth = "56px" as const;
export const componentSidebarBackground = "#F2F2F2" as const;
export const componentSidebarDarkBackground = "oklch(0.20 0.03 165)" as const;
export const componentSidebarBorder = "#DCE6E2" as const;
export const componentChartPrimary = "oklch(0.78 0.27 142)" as const;
export const componentChartSecondary = "oklch(0.88 0.05 175)" as const;
export const componentChartAccent = "oklch(0.65 0.10 180)" as const;
export const componentChartGrid = "#DCE6E2" as const;
export const componentChartBarRadius = "6px" as const;
export const componentEmptyMediaSize = "48px" as const;
export const componentEmptyTitleColor = "#073C2B" as const;
export const componentEmptyDescriptionColor = "rgba(16, 28, 35, 0.72)" as const;
export const componentEmptySurface = "#F2F2F2" as const;
export const componentLayoutMarketingColumns = "12" as const;
export const componentLayoutProductColumns = "8" as const;
export const componentLayoutCardGridMin = "280px" as const;
export const componentLayoutSectionPaddingDesktop = "96px" as const;
export const componentLayoutSectionPaddingMobile = "48px" as const;
